// Stage D (part 3) — emit_tests: render runnable vitest mapped 1:1 to obligation_keys.
// Removes E3's "spec is a doc, not code" implementer confound. SWU-ENG-007 (L1).
//
// Each obligation becomes exactly one `it.todo(...)` case. `it.todo` is chosen so the
// emitted file is BOTH syntactically valid TS *and* runnable as-is (todos report as
// pending, not failing) — the implementer fills each body by replacing `it.todo` with
// `it`. The 1:1 obligation_key↔test mapping is preserved in a leading comment per case.

import type { Obligation } from "../ir/types.js";

/** Escape a string for safe embedding inside a JS line comment. */
function commentSafe(s: string): string {
  return s.replace(/\r?\n/g, " ").replace(/\*\//g, "* /");
}

/** Render obligations as a runnable vitest file (1 `it.todo` per obligation_key). */
export function emitTests(obligations: readonly Obligation[]): string {
  const ordered = [...obligations].sort((a, b) =>
    a.obligation_key < b.obligation_key
      ? -1
      : a.obligation_key > b.obligation_key
        ? 1
        : 0,
  );
  const cases = ordered.map(
    (o) =>
      `  // obligation_key: ${o.obligation_key}\n` +
      `  // source: ${commentSafe(o.source_anchor)}\n` +
      `  it.todo(${JSON.stringify(`${o.rule_type}:${o.obligation_key.slice(0, 8)} ${o.description}`)});`,
  );
  return [
    `// AUTO-GENERATED by the deterministic test-derivation engine. Do not edit by hand.`,
    `// One it.todo per derived obligation_key; replace it.todo with it to implement.`,
    `import { describe, it } from "vitest";`,
    ``,
    `describe("derived obligations", () => {`,
    ...cases,
    `});`,
    ``,
  ].join("\n");
}
