-- ZagrMarketplaceV3.lean
-- Auto-generated by audit_richness.py from /Users/victorboscaro/domainspec-theorem/examples/zagr-marketplace.
-- v3 format: imports LeanCodeValidator.Report; #eval gradeFor spec
-- prints a CodegenReadinessReport.
--
-- Concepts: 53   Typed edges (in-graph): 49   Unresolved refs: 0   Profile: paperBaseline

import LeanCodeValidator.Report

namespace ZagrMarketplaceGen
open LeanCodeValidator

inductive Concept where
  | AcceptInvitation
  | AcceptInvitationWorkflow
  | AccessAuditLog
  | Address
  | ApproveNode
  | AuditAction
  | AuditLogQuery
  | AuditReasonRequirement
  | BankAccount
  | CorrectionRequest
  | DLocalStatusReadView
  | DataExport
  | DeletionRequest
  | DemoteAdmin
  | ExternalReferenceMapping
  | GrantRole
  | InboundDlocalStatusReadModel
  | Invitation
  | Invitation_lifecycle
  | InviteUser
  | KYBSnapshot
  | LastAdminInvariant
  | LegalEntity
  | MarketplaceAPI
  | Node
  | NodeDeactivated
  | NodeDetailQuery
  | NodeReadyForRegistration
  | NodeRole
  | NodeState
  | Node_lifecycle
  | ProcessingSummaryQuery
  | ReactivateNode
  | ReadNodePII
  | RejectNode
  | RetentionAwareDeletionWorkflow
  | RevokeInvitation
  | RevokeRole
  | Role
  | SelfServiceDeletionWorkflow
  | SoftDeleteCascadeWorkflow
  | SoftDeleteNode
  | SoftDeletePredicate
  | Subtree
  | SubtreeNodeListQuery
  | SubtreeVisibilityPolicy
  | TaxIdType
  | TermsAcceptance
  | TermsTemplate
  | TreeShapeConstraint
  | User
  | UserListAtScopeQuery
  | UserRoleAssignment
  deriving DecidableEq, BEq, Repr

def metaOf : Concept → Meta
  | .AcceptInvitation => .Operation
  | .AcceptInvitationWorkflow => .Workflow
  | .AccessAuditLog => .Entity
  | .Address => .ValueObject
  | .ApproveNode => .Operation
  | .AuditAction => .Enum
  | .AuditLogQuery => .Query
  | .AuditReasonRequirement => .ValueObject
  | .BankAccount => .ValueObject
  | .CorrectionRequest => .Operation
  | .DLocalStatusReadView => .Query
  | .DataExport => .Query
  | .DeletionRequest => .Operation
  | .DemoteAdmin => .Operation
  | .ExternalReferenceMapping => .Mapping
  | .GrantRole => .Operation
  | .InboundDlocalStatusReadModel => .Interface
  | .Invitation => .Entity
  | .Invitation_lifecycle => .StateMachine
  | .InviteUser => .Operation
  | .KYBSnapshot => .Entity
  | .LastAdminInvariant => .Rule
  | .LegalEntity => .ValueObject
  | .MarketplaceAPI => .Interface
  | .Node => .Entity
  | .Node_lifecycle => .StateMachine
  | .NodeDeactivated => .Event
  | .NodeDetailQuery => .Query
  | .NodeReadyForRegistration => .Event
  | .NodeRole => .Enum
  | .NodeState => .Enum
  | .ProcessingSummaryQuery => .Query
  | .ReactivateNode => .Operation
  | .ReadNodePII => .Operation
  | .RejectNode => .Operation
  | .RetentionAwareDeletionWorkflow => .Workflow
  | .RevokeInvitation => .Operation
  | .RevokeRole => .Operation
  | .Role => .Enum
  | .SelfServiceDeletionWorkflow => .Workflow
  | .SoftDeleteCascadeWorkflow => .Workflow
  | .SoftDeleteNode => .Operation
  | .SoftDeletePredicate => .StateMachine
  | .Subtree => .Query
  | .SubtreeNodeListQuery => .Query
  | .SubtreeVisibilityPolicy => .Policy
  | .TaxIdType => .Enum
  | .TermsAcceptance => .Entity
  | .TermsTemplate => .Entity
  | .TreeShapeConstraint => .Rule
  | .User => .Entity
  | .UserListAtScopeQuery => .Query
  | .UserRoleAssignment => .Entity

def conceptSpace : ConceptSpace where
  Concept  := Concept
  decEq    := inferInstance
  beq      := inferInstance
  concepts := [
    .AcceptInvitation,
    .AcceptInvitationWorkflow,
    .AccessAuditLog,
    .Address,
    .ApproveNode,
    .AuditAction,
    .AuditLogQuery,
    .AuditReasonRequirement,
    .BankAccount,
    .CorrectionRequest,
    .DLocalStatusReadView,
    .DataExport,
    .DeletionRequest,
    .DemoteAdmin,
    .ExternalReferenceMapping,
    .GrantRole,
    .InboundDlocalStatusReadModel,
    .Invitation,
    .Invitation_lifecycle,
    .InviteUser,
    .KYBSnapshot,
    .LastAdminInvariant,
    .LegalEntity,
    .MarketplaceAPI,
    .Node,
    .NodeDeactivated,
    .NodeDetailQuery,
    .NodeReadyForRegistration,
    .NodeRole,
    .NodeState,
    .Node_lifecycle,
    .ProcessingSummaryQuery,
    .ReactivateNode,
    .ReadNodePII,
    .RejectNode,
    .RetentionAwareDeletionWorkflow,
    .RevokeInvitation,
    .RevokeRole,
    .Role,
    .SelfServiceDeletionWorkflow,
    .SoftDeleteCascadeWorkflow,
    .SoftDeleteNode,
    .SoftDeletePredicate,
    .Subtree,
    .SubtreeNodeListQuery,
    .SubtreeVisibilityPolicy,
    .TaxIdType,
    .TermsAcceptance,
    .TermsTemplate,
    .TreeShapeConstraint,
    .User,
    .UserListAtScopeQuery,
    .UserRoleAssignment
  ]
  metaOf   := metaOf

def edges : List (EdgeRow .paperBaseline conceptSpace) := [
  { src := .AcceptInvitationWorkflow, edge := .orchestrates, tgt := .AcceptInvitation,
    provenance := .declared, wellTyped := rfl },
  { src := .AcceptInvitationWorkflow, edge := .orchestrates, tgt := .ApproveNode,
    provenance := .declared, wellTyped := rfl },
  { src := .ApproveNode, edge := .produces, tgt := .NodeReadyForRegistration,
    provenance := .declared, wellTyped := rfl },
  { src := .AuditLogQuery, edge := .queries, tgt := .AccessAuditLog,
    provenance := .declared, wellTyped := rfl },
  { src := .DLocalStatusReadView, edge := .queries, tgt := .Node,
    provenance := .declared, wellTyped := rfl },
  { src := .DataExport, edge := .queries, tgt := .AccessAuditLog,
    provenance := .declared, wellTyped := rfl },
  { src := .DataExport, edge := .queries, tgt := .KYBSnapshot,
    provenance := .declared, wellTyped := rfl },
  { src := .DataExport, edge := .queries, tgt := .Node,
    provenance := .declared, wellTyped := rfl },
  { src := .DataExport, edge := .queries, tgt := .TermsAcceptance,
    provenance := .declared, wellTyped := rfl },
  { src := .DataExport, edge := .queries, tgt := .User,
    provenance := .declared, wellTyped := rfl },
  { src := .ExternalReferenceMapping, edge := .maps, tgt := .InboundDlocalStatusReadModel,
    provenance := .declared, wellTyped := rfl },
  { src := .ExternalReferenceMapping, edge := .maps, tgt := .Node,
    provenance := .declared, wellTyped := rfl },
  { src := .Invitation, edge := .performs, tgt := .AcceptInvitation,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .DeletionRequest,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .DemoteAdmin,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .GrantRole,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .InviteUser,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .RevokeInvitation,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .RevokeRole,
    provenance := .declared, wellTyped := rfl },
  { src := .LastAdminInvariant, edge := .enforces, tgt := .SoftDeleteNode,
    provenance := .declared, wellTyped := rfl },
  { src := .NodeDeactivated, edge := .transitions, tgt := .SoftDeletePredicate,
    provenance := .declared, wellTyped := rfl },
  { src := .NodeDetailQuery, edge := .queries, tgt := .AccessAuditLog,
    provenance := .declared, wellTyped := rfl },
  { src := .NodeDetailQuery, edge := .queries, tgt := .Node,
    provenance := .declared, wellTyped := rfl },
  { src := .NodeReadyForRegistration, edge := .transitions, tgt := .Node_lifecycle,
    provenance := .declared, wellTyped := rfl },
  { src := .ProcessingSummaryQuery, edge := .queries, tgt := .AccessAuditLog,
    provenance := .declared, wellTyped := rfl },
  { src := .ProcessingSummaryQuery, edge := .queries, tgt := .KYBSnapshot,
    provenance := .declared, wellTyped := rfl },
  { src := .ProcessingSummaryQuery, edge := .queries, tgt := .User,
    provenance := .declared, wellTyped := rfl },
  { src := .SelfServiceDeletionWorkflow, edge := .orchestrates, tgt := .DeletionRequest,
    provenance := .declared, wellTyped := rfl },
  { src := .SoftDeleteCascadeWorkflow, edge := .orchestrates, tgt := .SoftDeleteNode,
    provenance := .declared, wellTyped := rfl },
  { src := .SoftDeleteNode, edge := .produces, tgt := .NodeDeactivated,
    provenance := .declared, wellTyped := rfl },
  { src := .Subtree, edge := .queries, tgt := .Node,
    provenance := .declared, wellTyped := rfl },
  { src := .SubtreeNodeListQuery, edge := .queries, tgt := .Node,
    provenance := .declared, wellTyped := rfl },
  { src := .SubtreeNodeListQuery, edge := .queries, tgt := .User,
    provenance := .declared, wellTyped := rfl },
  { src := .TreeShapeConstraint, edge := .enforces, tgt := .AcceptInvitation,
    provenance := .declared, wellTyped := rfl },
  { src := .TreeShapeConstraint, edge := .enforces, tgt := .InviteUser,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .ApproveNode,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .CorrectionRequest,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .DeletionRequest,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .DemoteAdmin,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .GrantRole,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .InviteUser,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .ReactivateNode,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .ReadNodePII,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .RejectNode,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .RevokeInvitation,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .RevokeRole,
    provenance := .declared, wellTyped := rfl },
  { src := .User, edge := .performs, tgt := .SoftDeleteNode,
    provenance := .declared, wellTyped := rfl },
  { src := .UserListAtScopeQuery, edge := .queries, tgt := .User,
    provenance := .declared, wellTyped := rfl },
  { src := .UserListAtScopeQuery, edge := .queries, tgt := .UserRoleAssignment,
    provenance := .declared, wellTyped := rfl }
]

def spec : Spec where
  profile        := .paperBaseline
  conceptSpace   := conceptSpace
  edges          := edges
  unresolvedRefs := []
  conceptCount   := 53

#eval gradeFor spec

end ZagrMarketplaceGen
