#!/usr/bin/env bash
# infra/setup.sh — Automated VPS setup for {project-name}
# Generated by domainspec-infra-architecture skill
# Usage: ./infra/setup.sh
# Prerequisites: pulumi logged in, DIGITALOCEAN_TOKEN and CLOUDFLARE_API_TOKEN set or in Pulumi config
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SSH_KEY_PATH="$HOME/.ssh/{project-name}-deploy"
STACK_NAME="production"
VPS_USER="deploy"
APP_DIR="/opt/{project-name}"

export PATH="$HOME/.pulumi/bin:$PATH"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
err()   { echo -e "${RED}[✗]${NC} $1" >&2; }
step()  { echo -e "\n${GREEN}==>${NC} $1"; }

# --- Preflight ---
step "Preflight checks"

command -v pulumi >/dev/null 2>&1 || { err "pulumi not found. Run: curl -fsSL https://get.pulumi.com | sh"; exit 1; }
command -v ssh    >/dev/null 2>&1 || { err "ssh not found"; exit 1; }
command -v scp    >/dev/null 2>&1 || { err "scp not found"; exit 1; }

info "pulumi $(pulumi version)"

# --- SSH Key ---
step "SSH deploy key"

if [[ -f "$SSH_KEY_PATH" ]]; then
  info "Key exists: $SSH_KEY_PATH"
else
  ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -N "" -C "{project-name}-deploy"
  info "Generated: $SSH_KEY_PATH"
fi

# --- Pulumi Stack ---
step "Pulumi stack"

cd "$SCRIPT_DIR"
npm ci --silent 2>/dev/null || npm install --silent

if pulumi stack ls 2>/dev/null | grep -q "$STACK_NAME"; then
  pulumi stack select "$STACK_NAME"
  info "Selected stack: $STACK_NAME"
else
  pulumi stack init "$STACK_NAME"
  info "Created stack: $STACK_NAME"
fi

# --- Config ---
step "Pulumi config"

# Set SSH key if not already set
CURRENT_KEY=$(pulumi config get {pulumi-project-name}:sshPublicKey 2>/dev/null || echo "")
if [[ -z "$CURRENT_KEY" ]]; then
  pulumi config set {pulumi-project-name}:sshPublicKey "$(cat "$SSH_KEY_PATH.pub")"
  info "Set sshPublicKey"
else
  info "sshPublicKey already configured"
fi

# Set domain if not set
CURRENT_DOMAIN=$(pulumi config get {pulumi-project-name}:domain 2>/dev/null || echo "")
if [[ -z "$CURRENT_DOMAIN" ]]; then
  read -rp "Domain (e.g. example.com): " DOMAIN
  pulumi config set {pulumi-project-name}:domain "$DOMAIN"
else
  DOMAIN="$CURRENT_DOMAIN"
  info "Domain: $DOMAIN"
fi

# Set DO token if not set
if ! pulumi config get digitalocean:token >/dev/null 2>&1; then
  if [[ -n "${DIGITALOCEAN_TOKEN:-}" ]]; then
    pulumi config set --secret digitalocean:token "$DIGITALOCEAN_TOKEN"
    info "Set digitalocean:token from env"
  else
    read -rsp "DigitalOcean API token: " DO_TOKEN; echo
    pulumi config set --secret digitalocean:token "$DO_TOKEN"
    info "Set digitalocean:token"
  fi
else
  info "digitalocean:token already configured"
fi

# Set CF token if not set
if ! pulumi config get cloudflare:apiToken >/dev/null 2>&1; then
  if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    pulumi config set --secret cloudflare:apiToken "$CLOUDFLARE_API_TOKEN"
    info "Set cloudflare:apiToken from env"
  else
    read -rsp "Cloudflare API token: " CF_TOKEN; echo
    pulumi config set --secret cloudflare:apiToken "$CF_TOKEN"
    info "Set cloudflare:apiToken"
  fi
else
  info "cloudflare:apiToken already configured"
fi

# --- Provision ---
step "Provisioning infrastructure"

pulumi up --yes

DROPLET_IP=$(pulumi stack output dropletIp)
info "Droplet IP: $DROPLET_IP"

# --- Wait for cloud-init ---
step "Waiting for VPS cloud-init to finish"

echo -n "Waiting for SSH..."
for i in $(seq 1 30); do
  if ssh -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 root@"$DROPLET_IP" "true" 2>/dev/null; then
    echo " OK"
    break
  fi
  echo -n "."
  if [[ $i -eq 30 ]]; then
    err "SSH not available after 5 minutes"
    exit 1
  fi
done

ssh -i "$SSH_KEY_PATH" root@"$DROPLET_IP" "cloud-init status --wait" 2>&1 | tail -1
info "Cloud-init complete"

# Verify Docker
ssh -i "$SSH_KEY_PATH" root@"$DROPLET_IP" "docker --version" 2>&1
info "Docker ready"

# --- Copy files ---
step "Copying production stack to VPS"

scp -i "$SSH_KEY_PATH" \
  "$SCRIPT_DIR/docker-compose.prod.yml" \
  "$SCRIPT_DIR/Caddyfile" \
  "$SCRIPT_DIR/prometheus.yml" \
  "$SCRIPT_DIR/.env.example" \
  root@"$DROPLET_IP":"$APP_DIR/"

scp -i "$SSH_KEY_PATH" -r \
  "$SCRIPT_DIR/alerts" \
  "$SCRIPT_DIR/grafana" \
  root@"$DROPLET_IP":"$APP_DIR/"

info "Files copied"

# --- Generate secrets ---
step "Generating secrets on VPS"

PROM_PASSWORD=$(openssl rand -base64 12 | tr -d '=+/' | head -c 12)

ssh -i "$SSH_KEY_PATH" root@"$DROPLET_IP" bash -s -- "$PROM_PASSWORD" "$APP_DIR" << 'REMOTE_EOF'
set -e
PROM_PLAIN="$1"
APP_DIR="$2"
cd "$APP_DIR"

DB_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/' | head -c 32)
JWT_SECRET=$(openssl rand -base64 32 | tr -d '=+/' | head -c 32)
GRAFANA_PASSWORD=$(openssl rand -base64 16 | tr -d '=+/' | head -c 16)

docker pull caddy:2-alpine >/dev/null 2>&1
PROMETHEUS_HASH=$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "$PROM_PLAIN")

cat > .env << EOF
DB_PASSWORD=$DB_PASSWORD
JWT_SECRET=$JWT_SECRET
GRAFANA_PASSWORD=$GRAFANA_PASSWORD
PROMETHEUS_HASH=$PROMETHEUS_HASH
IMAGE_TAG=latest
EOF

chmod 600 .env

# Setup deploy user SSH
mkdir -p /home/deploy/.ssh
cp /root/.ssh/authorized_keys /home/deploy/.ssh/authorized_keys
chown -R deploy:deploy /home/deploy/.ssh
chmod 700 /home/deploy/.ssh
chmod 600 /home/deploy/.ssh/authorized_keys

chown -R deploy:deploy "$APP_DIR"
REMOTE_EOF

info "Secrets generated"
warn "Prometheus UI password: $PROM_PASSWORD (save this!)"

# --- Verify ---
step "Verification"

ssh -i "$SSH_KEY_PATH" deploy@"$DROPLET_IP" "ls -la $APP_DIR/.env && echo 'deploy user SSH: OK'"
info "VPS fully configured"

# --- Summary ---
step "Setup complete"

echo ""
echo "  Droplet IP:    $DROPLET_IP"
echo "  App URL:       https://$DOMAIN"
echo "  API URL:       https://api.$DOMAIN"
echo "  Grafana:       https://grafana.$DOMAIN"
echo "  Prometheus:    https://prometheus.$DOMAIN (user: admin)"
echo ""
echo "  GitHub Secrets to add:"
echo "    VPS_HOST     = $DROPLET_IP"
echo "    VPS_SSH_KEY  = (contents of $SSH_KEY_PATH)"
echo ""
echo "  Then push to main to trigger the first deploy."
